apiVersion: v1
kind: ServiceAccount
metadata:
  name: graphite-cluster-sa
  namespace: monitoring
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: endpoints-reader
  namespace: monitoring
rules:
- apiGroups: [""]
  resources: ["endpoints"]
  verbs: ["get", "watch", "list"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: read-endpoints
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: endpoints-reader
subjects:
- kind: ServiceAccount
  name: graphite-cluster-sa
  namespace: monitoring
